# Generated by Django 4.2 on 2025-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='任务编号')),
                ('type', models.CharField(choices=[('dispute', '纠纷'), ('legal_aid', '法律援助')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('assigned', '已分配'), ('processing', '进行中'), ('completed', '已完成')], default='reported', max_length=20, verbose_name='状态')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='涉及金额')),
                ('party_name', models.CharField(max_length=50, verbose_name='当事人姓名')),
                ('party_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='当事人电话')),
                ('party_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='当事人住址')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('report_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='上报经度')),
                ('report_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='上报纬度')),
                ('report_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='上报地址')),
                ('report_image_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='上报图片ID')),
                ('report_file_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='上报文件ID')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('process_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='进行中提交时间')),
                ('participants', models.CharField(blank=True, max_length=500, null=True, verbose_name='参与人员')),
                ('handle_method', models.CharField(blank=True, choices=[('onsite', '到达现场'), ('online', '线上沟通')], max_length=20, null=True, verbose_name='处理方式')),
                ('expected_plan', models.TextField(blank=True, null=True, verbose_name='预计调解方案')),
                ('result', models.CharField(blank=True, choices=[('success', '成功'), ('failure', '失败'), ('partial', '部分成功')], max_length=20, null=True, verbose_name='调解结果')),
                ('result_detail', models.TextField(blank=True, null=True, verbose_name='结果详情')),
                ('process_description', models.TextField(blank=True, null=True, verbose_name='调解过程描述')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('complete_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='完成经度')),
                ('complete_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='完成纬度')),
                ('complete_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='完成地址')),
                ('complete_image_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='完成图片ID')),
                ('complete_file_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='完成文件ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'cases_task',
                'ordering': ['-reported_at', '-id'],
            },
        ),
    ]
