# Generated by Django 4.2 on 2026-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='序号')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请人')),
                ('respondent', models.CharField(max_length=100, verbose_name='被申请人')),
                ('case_reason', models.TextField(verbose_name='案由')),
                ('acceptance_time', models.DateField(verbose_name='受理时间')),
                ('handler', models.CharField(max_length=100, verbose_name='承办人员')),
                ('applicable_procedure', models.TextField(verbose_name='适用程序')),
                ('closure_time', models.DateField(verbose_name='结案时间')),
                ('closure_method', models.TextField(verbose_name='结案方式')),
                ('case_number', models.TextField(verbose_name='案号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '案件归档',
                'verbose_name_plural': '案件归档',
                'db_table': 'cases_case_archive',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_archive/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '归档附件',
                'verbose_name_plural': '归档附件',
                'db_table': 'cases_case_archive_file',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='任务编号')),
                ('status', models.CharField(choices=[('reported', '已上报'), ('assigned', '已分配'), ('processing', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='reported', max_length=20, verbose_name='状态')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='涉及金额')),
                ('party_name', models.CharField(max_length=50, verbose_name='当事人姓名')),
                ('party_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='当事人电话')),
                ('party_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='当事人住址')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('report_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='上报经度')),
                ('report_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='上报纬度')),
                ('report_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='上报地址')),
                ('report_image_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='上报图片ID')),
                ('report_file_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='上报文件ID')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('process_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='进行中提交时间')),
                ('participants', models.CharField(blank=True, max_length=500, null=True, verbose_name='参与人员')),
                ('handle_method', models.CharField(blank=True, choices=[('onsite', '到达现场'), ('online', '线上沟通')], max_length=20, null=True, verbose_name='处理方式')),
                ('expected_plan', models.TextField(blank=True, null=True, verbose_name='预计调解方案')),
                ('result', models.CharField(blank=True, choices=[('success', '成功'), ('failure', '失败'), ('partial', '部分成功')], max_length=20, null=True, verbose_name='调解结果')),
                ('result_detail', models.TextField(blank=True, null=True, verbose_name='结果详情')),
                ('process_description', models.TextField(blank=True, null=True, verbose_name='调解过程描述')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('complete_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='完成经度')),
                ('complete_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='完成纬度')),
                ('complete_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='完成地址')),
                ('complete_image_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='完成图片ID')),
                ('complete_file_ids', models.CharField(blank=True, default='', max_length=500, verbose_name='完成文件ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'cases_task',
                'ordering': ['-reported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务类型',
                'verbose_name_plural': '任务类型',
                'db_table': 'cases_task_type',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='镇名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '所属镇',
                'verbose_name_plural': '所属镇',
                'db_table': 'cases_town',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
