# Generated by Django 4.2 on 2026-02-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('grids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_handle', to=settings.AUTH_USER_MODEL, verbose_name='被分配调解员'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='分配人'),
        ),
        migrations.AddField(
            model_name='task',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='grids.grid', verbose_name='所属网格'),
        ),
        migrations.AddField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cases.tasktype', verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cases.town', verbose_name='所属镇'),
        ),
        migrations.AddField(
            model_name='casearchivefile',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cases.casearchive', verbose_name='所属归档案件'),
        ),
        migrations.CreateModel(
            name='ArchivedTask',
            fields=[
            ],
            options={
                'verbose_name': '任务归档',
                'verbose_name_plural': '任务归档',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.task',),
        ),
        migrations.CreateModel(
            name='TaskStatReport',
            fields=[
            ],
            options={
                'verbose_name': '统计报表',
                'verbose_name_plural': '统计报表',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.task',),
        ),
        migrations.CreateModel(
            name='UnassignedTask',
            fields=[
            ],
            options={
                'verbose_name': '待分配任务',
                'verbose_name_plural': '待分配任务',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.task',),
        ),
    ]
