# Generated by Django 4.2 on 2025-12-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnassignedTask',
            fields=[
            ],
            options={
                'verbose_name': '待分配任务',
                'verbose_name_plural': '待分配任务',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.task',),
        ),
    ]
