# Generated by Django 4.2 on 2026-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_tasktype_town_remove_task_type_alter_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='序号')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请人')),
                ('respondent', models.CharField(max_length=100, verbose_name='被申请人')),
                ('case_reason', models.TextField(verbose_name='案由')),
                ('acceptance_time', models.DateField(verbose_name='受理时间')),
                ('handler', models.CharField(max_length=100, verbose_name='承办人员')),
                ('applicable_procedure', models.TextField(verbose_name='适用程序')),
                ('closure_time', models.DateField(verbose_name='结案时间')),
                ('closure_method', models.TextField(verbose_name='结案方式')),
                ('case_number', models.TextField(verbose_name='案号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '案件归档',
                'verbose_name_plural': '案件归档',
                'db_table': 'cases_case_archive',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedTask',
            fields=[
            ],
            options={
                'verbose_name': '任务归档',
                'verbose_name_plural': '任务归档',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.task',),
        ),
    ]
