# Generated by Django 4.2 on 2026-02-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casearchive_archivedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatReport',
            fields=[
            ],
            options={
                'verbose_name': '统计报表',
                'verbose_name_plural': '统计报表',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.task',),
        ),
    ]
