# Generated by Django 4.2 on 2026-02-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_taskstatreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='town',
            name='code',
        ),
    ]
