# Generated by Django 4.2 on 2026-02-10 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_code_from_tasktype_and_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_archive/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cases.casearchive', verbose_name='所属归档案件')),
            ],
            options={
                'verbose_name': '归档附件',
                'verbose_name_plural': '归档附件',
                'db_table': 'cases_case_archive_file',
                'ordering': ['id'],
            },
        ),
    ]
