# Generated by Django 4.2 on 2026-02-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/%Y/%m/', verbose_name='头像')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('grid_manager', '网格负责人'), ('mediator', '调解员')], default='mediator', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='grids.grid', verbose_name='所属网格')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='UserAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='users/%Y/%m/', verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'users_attachment',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='培训名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='培训内容')),
                ('training_time', models.DateField(blank=True, null=True, verbose_name='培训时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('files', models.ManyToManyField(blank=True, related_name='training_records', to='users.userattachment', verbose_name='证书附件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
                'db_table': 'users_training_record',
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('period', models.CharField(help_text='格式：YYYY-MM', max_length=20, verbose_name='考核周期')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores_received', to=settings.AUTH_USER_MODEL, verbose_name='调解员')),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores_given', to=settings.AUTH_USER_MODEL, verbose_name='打分人')),
            ],
            options={
                'verbose_name': '绩效打分',
                'verbose_name_plural': '绩效打分',
                'db_table': 'users_performance_score',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机构名称')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='标签')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.organization', verbose_name='上级机构')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'db_table': 'users_organization',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.organization', verbose_name='所属机构'),
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
            ],
            options={
                'verbose_name': '历史绩效',
                'verbose_name_plural': '历史绩效',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.performancescore',),
        ),
        migrations.AddConstraint(
            model_name='performancescore',
            constraint=models.UniqueConstraint(fields=('mediator', 'period'), name='uniq_users_score_mediator_period'),
        ),
    ]
