# Generated by Django 4.2 on 2025-12-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
            ],
            options={
                'verbose_name': '历史绩效',
                'verbose_name_plural': '历史绩效',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.performancescore',),
        ),
    ]
