# Generated by Django 4.2 on 2026-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='标签'),
        ),
    ]
