# Generated by Django 4.2 on 2026-02-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_organization_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
    ]
