# Generated by Django 4.2 on 2025-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('document', '文档')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='文件大小')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始文件名')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'common_attachment',
            },
        ),
        migrations.CreateModel(
            name='MapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_level', models.IntegerField(default=12, verbose_name='缩放级别(3-20)')),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='中心点经度')),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='中心点纬度')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '地图配置',
                'verbose_name_plural': '地图配置',
                'db_table': 'common_map_config',
            },
        ),
    ]
