# Generated by Django 4.2 on 2025-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网格名称')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属区域')),
                ('boundary', models.JSONField(blank=True, help_text='[[lng, lat], ...]', null=True, verbose_name='边界坐标')),
                ('center_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='中心点经度')),
                ('center_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='中心点纬度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='网格描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网格',
                'verbose_name_plural': '网格',
                'db_table': 'grids_grid',
            },
        ),
    ]
