# Generated by Django 4.2 on 2025-12-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to='content/%Y/%m/', verbose_name='文件'),
        ),
    ]
