# Generated by Django 4.2 on 2026-02-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_article_view_log'),
        ('content', '0005_articleviewlog'),
    ]

    operations = [
    ]
